#image: hpccsystems/clienttools
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - https://github.com/hpcc-systems/vscode-ecl/releases/latest/download/hpcc-systems.ecl.vsix
    - https://github.com/GordonSmith/vscode-ojs/releases/latest/download/gordonsmith.observable-js.vsix
